### ISSUE TITLE
Checklist of things that need to be done

### ISSUE THREAD

**Issue by ahmedali8** [defientco/crea8ors-subscription-contracts#1]
# Project Todo List

## Project Setup
- [x] #6
- [x] #2
    - [x] #7
    - [ ] Follow crea8ors main repo standards
    - [ ] Add Architecture.md
    - [ ] Add Contributing.md
    - [x] #13

## Smart Contract Development
- [x] Start POC
    - [x] #5
    - [x] Design the contract to be modular
    - [x] #3
    - [x] Implement fallback architecture for reliability
    - [x] Handle subscribe and ownerOf functionality through fallback
- [x] Features:
    - [x] #9
    - [x] Finalize modular architecture
    - [x] #8
    - [x] Implement subscription interval functionality
    - [x] Set renewal prices for subscriptions
    - [x] Define maximum duration for a single purchase or extension (e.g., 1000 months)
    - [x] Create setter functions for required parameters
    - [x] Access control according to crea8ors requirements
    - [x] Add erc20 transfer helper library for consistency
- [x] #14

## Testing
- [x] Setup test suite structure
- [x] Write foundry tests
    - [x] Unit tests
    - [x] Integration tests
    - [x] Fuzz testing (if applicable)

## Documentation
- [ ] Create an issue template
- [ ] Write Natspec comments for the smart contracts
- [ ] Update the README file

## Integration with cre8ors
- [x] #10

## Integration with Minter (FriendsAndFamilyMinter)
- [x] #11
